toy-mongo/config/routes.rb
Rails.application.routes.draw do
    resources :microposts, except: [:show]
    resources :users, except: [:show]

    root to: "microposts#index"
end

toy-mongo/app/models/micropost.rb
class Micropost
  include Mongoid::Document
  belongs_to :user
  validates :content, length: {maximum: 140}
                      presence: true

  field :content, type: String
  field :user_id, type: Integer
end

toy-mongo/app/models/user.rb
class User
  include Mongoid::Document
  has_many :microposts
  validates :name, presence: true
  validates :email, presence: true

  field :name, type: String
  field :email, type: String
end

toy-mongo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

toy-mongo/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def index
      @microposts = Micropost.all
  end

  def new
      @micropost = Micropost.new
  end

  def create
      @micropost = Micropost.new(post_params)

      if @micropost.save
          redirect_to microposts_path, notice: "Post has been created" and return
      end
  end

  def edit
      @micropost = Micropost.find(params[:id])
  end

  def update
      @micropost = Micropost.find(params[:id])

      if @micropost.update_attributes(post_params)
          redirect_to microposts_path, notice: "Post has been updated!" and return
      end
  end

  def destroy
      @micropost = Micropost.find(params[:id])
      @micropost.destroy

      redirect_to microposts_path, notice: "Post has been deleted!" and return
 
  end

  private def post_params
      params.require(:micropost).permit(:content, :user_id)
  end
end

toy-mongo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all
  end

  def new
      @user = User.new
  end

  def create
      @user = User.new(user_params)

      if @user.save
          redirect_to users_path, notice: "The user has been created!" and return
      end
      render 'new'
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])

      if @user.update_attributes(user_params)
          redirect_to users_path, notice: "#{@user.name} has been updated!" and return
      end
      
      render 'edit'
  end

  def destroy
      @user = User.find(params[:id])
      @user.destroy

      redirect_to users_path, notice: "#{@user.name} has been deleted!" and return
  end

  private def user_params
      params.require(:user).permit(:name, :email)
  end

end

toy-mongo/app/helpers/application_helper.rb
module ApplicationHelper
end

toy-mongo/app/helpers/microposts_helper.rb
module MicropostsHelper
end

toy-mongo/app/helpers/users_helper.rb
module UsersHelper
end

toy-mongo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toy</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

toy-mongo/app/views/microposts/_form.html.erb
<%= form_for @micropost do |f| %>
    <div class="form-group">
<%= f.label :content %>
<%= f.text_field :content, class: "form-control" %>
</div>
<div class="form-group">
<%= f.label :user_id %>
<%= f.text_field :user_id, class: "form-control" %>
</div>
<%= f.submit class: "btn btn-primary" %>
<% end %>

toy-mongo/app/views/microposts/create.html.erb
<h1>Micropost#create</h1>
<p>Find me in app/views/micropost/create.html.erb</p>

toy-mongo/app/views/microposts/destroy.html.erb
<h1>Micropost#destroy</h1>
<p>Find me in app/views/micropost/destroy.html.erb</p>

toy-mongo/app/views/microposts/edit.html.erb
<h1>Edit Post</h1>
<div class="well">
  <%= render "form" %>
</div>

toy-mongo/app/views/microposts/index.html.erb
<h1>Posts</h1>
<div class="well">
  <%= link_to "New Post", new_micropost_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Content</th>
      <th>User ID</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @microposts.size == 0 %>
          <tr>
        <td colspan="6">No posts found.</td>
      </tr>
    <% else %>
          <% @microposts.each do |micropost| %>
            <tr>
          <td><%= micropost.content %></td>
          <td><%= micropost.user_id %></td>
          <td>
            <%= link_to "Edit", edit_micropost_path(micropost), class: "btn btn-default" %>
          </td>
          <td>
            <%= button_to "Delete", micropost, method: :delete, data: { confirm: "Are you sure you wish to delete this post?" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

toy-mongo/app/views/microposts/new.html.erb
<h1>New Post</h1>
<div class="well">
<%= render "form" %>
</div>

toy-mongo/app/views/microposts/show.html.erb
<h1>Micropost#show</h1>
<p>Find me in app/views/micropost/show.html.erb</p>

toy-mongo/app/views/microposts/update.html.erb
<h1>Micropost#update</h1>
<p>Find me in app/views/micropost/update.html.erb</p>

toy-mongo/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <div class="form-group">
<%= f.label :name %>
<%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
<%= f.label :email %>
<%= f.text_field :email, class: "form-control" %>
</div>
<%= f.submit class: "btn btn-primary" %>
<% end %>

toy-mongo/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

toy-mongo/app/views/users/destroy.html.erb
<h1>Users#destory</h1>
<p>Find me in app/views/users/destory.html.erb</p>

toy-mongo/app/views/users/edit.html.erb
<h1>Edit user</h1>
<div class="well">
    <%= render "form" %>
</div>

toy-mongo/app/views/users/index.html.erb
<h1>Users</h1>

<div class="well">
<%= link_to "New User", new_user_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
<thead>
<tr>
<th>Name</th>
<th>Email</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
</tr>
</thead>

<tbody>
<% if @users.size == 0 %>
    <tr>
<td colspan="6">No user found.</td>
</tr>
    <% else %>
    <% @users.each do |user| %>
    <tr>
<td><%= user.name %></td>
<td><%= user.email %></td>
<td>
<%= link_to "Edit", edit_user_path(user), class: "btn btn-default" %>
<td>
<%= button_to "Delete", user, method: :delete, data: { confirm: "Are you sure you wish to delete #{user.name}?" }, class: "btn btn-danger" %>
</td>
</tr>
<% end %>
<% end %>
</tbody>
</table>

toy-mongo/app/views/users/new.html.erb
<h1>New Person</h1>

<div class="well">
    <%= render "form" %>
</div>

toy-mongo/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>